name: Options @ 5pm

on:
  schedule:
    # Runs at 5 PM, Monday through Friday
    - cron: '0 1 * * 2-6'
  workflow_dispatch:

jobs:
  calculate_option_price:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This step ensures the options_data.json file is present in the working directory

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Set up Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y libglib2.0-0 libnss3 libgconf-2-4 libfontconfig1
          
      - name: Run the script
        run: |
          python -m Options.DataRetrieval  # Ensure this script reads from Options/options_data.json
        env:
          PYTHONPATH: ${{ github.workspace }}
