name: Public Update

on:
  # schedule:
  #   # Runs at 6:30 AM and 10 AM PST, Monday through Friday
  #   - cron: '30 13 * * 1-5'
  #   - cron: '0 17 * * 1-5'
  workflow_dispatch:

jobs:
  calculate_option_price:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          repository: miniquinox/Stock-Overlay
          ssh-strict: true
          persist-credentials: true
          clean: true
          fetch-depth: 1
          lfs: false
          submodules: false
          set-safe-directory: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Use the secret here 

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robin_stocks python-dotenv

      - name: Run the script
        run: |
          python -m Options.appUpdater
        env:
          PYTHONPATH: ${{ github.workspace }}
          ROBIN_MFA: ${{ secrets.ROBIN_MFA }}
          ROBIN_USERNAME: ${{ secrets.ROBIN_USERNAME }}
          ROBIN_PASSWORD: ${{ secrets.ROBIN_PASSWORD }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          CHAT_ID_TEST: ${{ secrets.CHAT_ID_TEST }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
